### PR TITLE
Fix all warnings in overlay processors

### PR DESCRIPTION
**Pull request by andresailer**

### CODE REVIEW

**Comment by gaede** [comment]
In FPCCDOverlayBX.h you need to replace:
StringVec   _mergeCollections{"VTXPixelHits VTXPixelHits"} ;

**Comment by gaede** [comment]
... with
StringVec   _mergeCollections{"VTXPixelHits", "VTXPixelHits"} ;

**Comment by andresailer** [comment]
Ok, changed. This line https://github.com/andresailer/Overlay/blob/06e8ff6a7c6950b7e44015da533c40dbabdf273c/src/FPCCDOverlayBX.cc#L80
got me a bit confused.

**Comment by gaede** [comment]
Ok I see, but this line is also wrong. Should be really:
 exMap.push_back( "VTXPixelHits");
 exMap.push_back("VTXPixelHits" );
or better in c++11
exMap{ "VTXPixelHits", "VTXPixelHits" } ;

**Comment by andresailer** [comment]
Even better is getting rid of the variable completely.
This should work as well, and we take the default from where we define it in one place
```c++
     registerOptionalParameter( "MergeCollections" ,
                                "Pairs of collection names with one bx to be overlayed (BG name first)"  ,
                                _mergeCollections ,
                                _mergeCollections ) ;
```

And then make a new function register(Optional)Parameter where the default is always taken from the third argument and we drop the fourth argument...

**Comment by gaede** [comment]
Hmm. Then I would prefer:
```c++
    registerOptionalParameter( "MergeCollections" ,
                   "Pairs of collection names with one bx to be overlayed (BG name first)"  ,
                   _mergeCollections ,
                   {"VTXPixelHits","VTXPixelHits"} ) ;
```
as one has all the default values in the .cc file rather then the header...

**Comment by gaede** [comment]
... and probably have 
```
 StringVec _mergeCollections{} ;
```
in the header to not confuse everyone ...

**Comment by andresailer** [comment]
I put `{"VTXPixelHits","VTXPixelHits"}` in the cc already. I don't want to change all the values again, anyway they should be consistent

**Pull request merged**
